<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>CP1_CursoTec.Application</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CP1-CursoTec.Domain\CP1-CursoTec.Domain.csproj" />
    </ItemGroup>

</Project>
